### ISSUE TITLE
lacks clarity on how to use

### ISSUE THREAD

**Issue by deresegetachew** [rusty1s/mongoose-i18n-error#1]
i was confused going through the read.me file ;  where am I suppose to define this code snippet ? 

```
{
    username: {
        type: 'required',
        message: 'is required',
        value: undefined
    },
    email: {
        type: 'regexp',
        message: 'is no valid email',
        value: 'johndoe.de'
    }
}
```

it would be very helpful if you had a working example.  Thanks!

**Comment by rusty1s** [comment]
You don't have to put that anywhere. This is just a basic example of the error message that this plugin provides on an error. See the usage section for implementation details. If you have any questions, do not hesitate to write here again.
